// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"30","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"YEP_FpsSynchOption","status":true,"description":"v1.02 Adds a new command to Options menu for synching\r\nthe FPS of moniters with higher FPS rates.","parameters":{"Command Name":"Synch Monitor FPS","Default Setting":"true"}},
{"name":"KMS_AccelerateFileScene","status":true,"description":"[v0.1.0] セーブ/ロード画面の描画を高速化します。","parameters":{}},
{"name":"MessageWindowPopup","status":true,"description":"フキダシウィンドウプラグイン","parameters":{"フォントサイズ":"22","余白":"10","自動設定":"true","フェイス倍率":"75","ウィンドウ連携":"true","行間":"4","ウィンドウ透過":"false","フォントサイズ増減幅":"12","フォントサイズ上限":"96","フォントサイズ下限":"24","画面内に収める":"true","振動の速さ":"5","振動時間":"60"}}
];
